@html{
    @body{
        @h1{
            Header!
        }
        
        @p{
            Paragraph 
             
            ~~~
             Look at this! @ @ @ @ @ @ { } { }
            ~~~

            @script{
                ~~~
                    var obj = {
                        test: "Hello!"
                    };

                    console.log(obj.test);

                    function test(){
                        console.log("it works");
                    }

                    test();
                ~~~
            }
        }
    }
}